package mypack;
// Generated Aug 25, 2019 9:05:10 AM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer serialNo;
     private String uname;
     private String mail;
     private String upassword;

    public Student() {
    }

    public Student(String uname, String mail, String upassword) {
       this.uname = uname;
       this.mail = mail;
       this.upassword = upassword;
    }
   
    public Integer getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(Integer serialNo) {
        this.serialNo = serialNo;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getUpassword() {
        return this.upassword;
    }
    
    public void setUpassword(String upassword) {
        this.upassword = upassword;
    }




}


